export const CATEGORIES = [
  "Advanced Facial",
  "Bikini & Brazilian Waxing",
  "Body Enhancement",
  "Body Waxing",
  "Face Waxing",
  "Facial Treatment",
  "Laser Hair Removal",
  "Lash Extension",
  "Lipolysis",
  "Massage",
  "Pedicure Treatment",
  "PRP Stretch Mark",
  "Semi Permanent Brows",
  "Skin IV Drips",
  "Skin Treatment",
  "Tattoo Removal",
  "Teeth Whitening",
  "Others",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const SERVICE_CATALOG: Record<string, string[]> = {
  "Advanced Facial": [
    "Advanced Acne Treatment",
    "Anti Wrinkles Treatment",
    "Chemical Peel (Pro)",
    "Chemical Peel",
    "Meso Therapy Facials",
    "PRP Vampire Facials",
    "PRP Body Therapy",
  ],
  "Bikini & Brazilian Waxing": [
    "Brazilian Waxing",
    "Bikini Full Waxing",
    "Bikini Line Waxing",
  ],
  "Body Enhancement": [
    "Back Folds",
    "Tummy Reduction",
    "Butt Vacuum Therapy",
    "Slim Waistline",
    "Breast Vacuum Therapy",
    "Hip Vacuum Therapy",
  ],
  "Body Waxing": [
    "Full Body Waxing",
    "Back Waxing (Half)",
    "Back Waxing (Full)",
    "Chest Waxing",
    "Leg Waxing (Half)",
    "Leg Waxing (Full)",
    "Arms Waxing (Half)",
    "Arms Waxing (Full)",
    "Stomach Waxing",
    "Underarms Waxing",
  ],
  "Face Waxing": [
    "Chin Waxing",
    "Full Face Waxing",
    "Sideburns Waxing",
    "Upper Lip Waxing",
    "Eyebrows Waxing",
  ],
  "Facial Treatment": [
    "Dermabrasion",
    "Anti Aging",
    "Acne Control Facials",
    "Basic Facials",
    "Derma Planning Deluxe",
    "Instant Glow Facials",
    "LED Therapy Facials",
    "Special Hydra Facials",
  ],
  "Laser Hair Removal": [
    "Neck",
    "Underarms",
    "Hands",
    "Legs (Half)",
    "Legs (Full)",
    "Bikini Line",
    "Bikini",
    "Brazilian (Men)",
    "Brazilian (Women)",
    "Chin (Women)",
    "Chin (Men)",
    "Upper Lip",
    "Half Face",
    "Full Face",
    "Chest",
    "Stomach",
    "Back",
    "Tummy Line",
    "Full Body",
  ],
  "Lash Extension": [
    "Volume Lashes",
    "Classic Lashes",
    "Color Effects",
    "Hybrid Lashes",
    "Mega Volume Lashes",
    "Undereye Lash",
    "Lash Removal",
  ],
  "Lipolysis": [
    "Lipolysis Treatment",
  ],
  "Massage": [
    "Deep Tissue Massage",
    "Full Body Massage",
    "Hot Stone Massage",
    "Swedish Massage",
  ],
  "Pedicure Treatment": [
    "Boom Pedicure",
    "Foot Detox",
    "Jelly Pedicure",
    "Pedicure & Manicure",
  ],
  "PRP Stretch Mark": [
    "PRP - Arm, Thigh, Chest & Butt",
    "PRP - Arm & Thigh",
    "PRP - Arm",
  ],
  "Semi Permanent Brows": [
    "Nano Combo Brows",
    "Micro Shading",
    "Signature Ombre Brows",
  ],
  "Skin IV Drips": [
    "Luminous Radiance",
    "Weight Loss IV",
    "Radiant Glow Infusion",
    "Vitamin B12 Boost",
    "Immune Booster",
    "Detox IV Therapy",
    "Billionaire Skin",
    "Diamond White Infusion",
    "Snow White IV",
  ],
  "Skin Treatment": [
    "Deluxe Body Polish",
    "Exfoliate Bath",
    "Full Body Glow Bath",
    "Golden Glow Sauna",
    "Morroccan Bath",
  ],
  "Tattoo Removal": [
    "Multiple Tattoo Removal",
    "Body Tattoo Removal",
    "Eyebrow Tattoo Removal",
  ],
  "Teeth Whitening": [
    "Teeth Whitening and Scaling",
    "Scaling",
    "Teeth Whitening",
  ],
  "Others": [],
};
